# Use the Open Source / Community image specifically
image:
  repository: localstack/localstack
  tag: "latest" # or a specific version like "3.0"

extraEnvVars:
  - name: SKIP_SSL_CERT_DOWNLOAD
    value: "1"
  - name: ACTIVATE_PRO
    value: "false"