name: Trigger Build in integration-ci-cd

on:
  push:
    tags:
      - 'v*'

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repository dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.REPO_ACCESS_PAT }}
          repository: kubecost/integration-ci-cd  # or your org/repo name
          event-type: finops-agent-release
          client-payload: '{"tag": "${{ github.ref_name }}"}'
